### ISSUE TITLE
Unexpected behavior of socket connection

### ISSUE THREAD

**Issue by waphumanoid** [nuclearace/Socket.IO-Client-Swift#31] opened 2015-03-26 09:59 UTC
Good day. I was working with the library all day long and unfortunately facing a lot of strange behavior. A socket connects pretty fast but then it looks like it often falls down (?) to long polling and cannot receive any message from a server. When I close a socket it can suddenly continue to reconnect repeatedly.
I've got a browser socket client running at the same time on the same mac and it receives messages just in time while the iOS client keeps silence (between reconnect attempts).

Attaching a log to show a regular case (I sent a lot of testing messages through the server before calling [socket closeWithFast:YES] method but no luck):

2015-03-26 19:29:26.344
parsePollingMessage: 2:40
Should do event: "connect" with data: "nil"
Sending ws: probe as type: 2
Sending poll:  as type: 6
2015-03-26 19:29:26.523

/*
Calling:
[socket on:@"connect" callback:^(NSArray *data, void (^ack)(NSArray *)) {
        [socket emitObjc:@"join room" withItems:@[@"/threads/drom-static/parom"]];
    }];
*/

Sending poll: 2["join room",["\/threads\/drom-static\/parom"]] as type: 4
2015-03-26 19:29:26.546
parsePollingMessage: 1:6
Sending ws:  as type: 5
parsePollingMessage: {"code":3,"message":"Bad request"}
Should do event: "reconnect" with data: "Optional([Error parsing XHR message])"
Should do event: "reconnectAttempt" with data: "Optional([-1])"
Sending ws: probe as type: 2
Sending poll:  as type: 6
Should do event: "reconnect" with data: "Optional([Socket Disconnect])"
Should do event: "reconnectAttempt" with data: "Optional([-2])"
parsePollingMessage: 2:40
Should do event: "connect" with data: "nil"
Sending ws:  as type: 5
Sending ws: probe as type: 2

/*
Calling:
[socket on:@"connect" callback:^(NSArray *data, void (^ack)(NSArray *)) {
        [socket emitObjc:@"join room" withItems:@[@"/threads/drom-static/parom"]];
    }];
*/

2015-03-26 19:29:27.041
Sending ws:  as type: 2
Sending ws:  as type: 2
Sending ws:  as type: 2
Sending ws:  as type: 2

/*
Calling:
[socket closeWithFast:YES];
*/

Should do event: "disconnect" with data: "Optional([Fast Disconnect])"
2015-03-26 19:30:26.389
Should do event: "reconnectAttempt" with data: "Optional([-1])"
Warning! This socket was previously closed. This might be dangerous!
Should do event: "reconnectAttempt" with data: "Optional([-2])"
2015-03-26 19:30:26.729
parsePollingMessage: 2:40
Should do event: "connect" with data: "nil"
2015-03-26 19:30:26.766

/*
Calling:
[socket on:@"connect" callback:^(NSArray *data, void (^ack)(NSArray *)) {
        [socket emitObjc:@"join room" withItems:@[@"/threads/drom-static/parom"]];
    }];
*/

Sending poll: 2["join room",["\/threads\/drom-static\/parom"]] as type: 4
Sending ws: probe as type: 2
parsePollingMessage: 2:40
Should do event: "connect" with data: "nil"
Sending ws: probe as type: 2
2015-03-26
Sending poll:  as type: 6
Sending poll:  as type: 6
pSarsePolelningMedssage: 1:i6
ng ws:  as type: 5
Sending ws: 2["join room",["\/threads\/drom-static\/parom"]] as type: 4

… repeated indefinitely

**Comment by nuclearace** [comment] 2015-03-26 13:01
Does it happen every time you try and close the socket?

**Comment by nuclearace** [comment] 2015-03-26 13:05
Also is this happening from a background task?

**Comment by nuclearace** [comment] 2015-03-26 15:10
@waphumanoid Where are you closing from

**Comment by waphumanoid** [comment] 2015-03-27 00:21
Well it happens very often maybe 8 times of 10.
I noticed that if I restart xcode/mac the "disconnect" event fires as expected first time but after that other attempts go wrong (using the xcode simulator and iphone as well).
I tested the disconnect method both from the main (1 case) and background (2 case) processes with the same result:
calling [self performSelector:@selector(closeIOSocket) withObject:nil afterDelay:10]; // <- from the main thread
after 10 secs it calls on the main thread:
(1 case):
- (void)closeIOSocket
{
    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        [chatIOSocket closeWithFast:YES];
        //chatIOSocket = nil;
    });
}
(2 case):
- (void)closeIOSocket
{
        [chatIOSocket closeWithFast:YES];
        //chatIOSocket = nil;
}

Actually I worry mostly about the sutiation when the socket doesn't get any message with the "connect" event successfully fired. I tie it with long polling mechanism but have no clear thoughts though.

**Comment by nuclearace** [comment] 2015-03-27 03:40
Are you forcing long polling? Also, unless you're calling `close` on a background queue, I wouldn't pass true to it. Fast closing basically assumes that the server will get the disconnect and immediately goes back to the disconnect handler.

Also just an aside: The framework wasn't really designed for Objective-C, since I don't really know it that well.

**Comment by nuclearace** [comment] 2015-03-27 03:46
Also, I'm not sure the client will fall back to long-polling unless it doesn't complete the WebSocket handshake. Since once it goes to WebSockets it'll try to reconnect if it loses connection.

**Comment by nuclearace** [comment] 2015-03-27 04:20
I just reread your OP

```
parsePollingMessage: 1:6
Sending ws: as type: 5
parsePollingMessage: {"code":3,"message":"Bad request"}
Should do event: "reconnect" with data: "Optional([Error parsing XHR message])"
```

In that case, `{"code":3,"message":"Bad request"}` could mean it got another polling message when it had switched to WS. And then the parsing error could've caused a reconnect loop, but I thought fixed that [here](https://github.com/nuclearace/Socket.IO-Client-Swift/blob/master/SwiftIO/SocketEngine.swift#L292) before I commited it.

**Comment by waphumanoid** [comment] 2015-03-27 05:08
No, I am not forcing long polling. I'd rather force ws for using its advatages but it's impossible with socketIO as far as I understand?

**Comment by nuclearace** [comment] 2015-03-27 05:10
It's something I've been meaning to add. 

Sent from my iPhone

**Comment by nuclearace** [comment] 2015-03-27 13:26
I'm adding a forceWebsocket option, testing it now

**Comment by markschmid** [comment] 2015-03-27 13:27
Cool, "forceWebsocket" would be something which we appreciate

**Comment by nuclearace** [comment] 2015-03-27 13:36
https://github.com/nuclearace/Socket.IO-Client-Swift/commit/98e0c355f945982a75b05ecb16d5cb77073fbd96

Looking okay so far, will probably merge in a few hours after I test some more.

**Comment by nuclearace** [comment] 2015-03-27 13:37
As for your original problem, I'm still having trouble reproducing

**Comment by nuclearace** [comment] 2015-03-27 16:46
v1.4.3 adds forceWebsockets

**Comment by waphumanoid** [comment] 2015-03-30 06:33
Yeah, the changes are working partly :).
I have tested 3 cases: default transport settings (hybrid), forcePolling, forceWebsockets. First two worked like before - sometimes it couldn't receive any message from server, after disconnect event fell down to reconnection. Particularly for forcePolling I've noticed this small thing (don't know maybe it's by design):
```
After calling closeWithFast method:
2015-03-30 16:19:48.083
Should do event: disconnect with data: Optional([Disconnect])
Sending poll:  as type: 1
1:6
{"code":1,"message":"Session ID unknown"}
2015-03-30 16:19:51.233 parsing error: {"code":1,"message":"Session ID unknown"}
2015-03-30 16:19:52.275 SocketIO: disconnected
```
And for forceWebsockets I can say only positive things so far. It works as expected right now.

**Comment by nuclearace** [comment] 2015-03-30 12:53
Are you connecting straight to the socket.io server? Or are you proxying through nginx or something similar?

**Comment by waphumanoid** [comment] 2015-03-31 06:13
yes, socket.io is proxying by nginx

**Comment by nuclearace** [comment] 2015-03-31 12:17
So it's probably related to https://github.com/socketio/socket.io-client-swift/issues/36

**Comment by waphumanoid** [comment] 2015-04-01 06:09
Hmmm, I asked our admin to review nginx settings, we added "proxy_buffering off;" (didn't affect anything at all) and changed this:
```
WAS: proxy_set_header Connection "upgrade";
NOW: proxy_set_header Connection "Upgrade";
```
And after that (uppercase U) it began to work in hybrid mode (with long polling) pretty well! No reconnections and so on...
But rarely after +/-5 minutes it suddenly begins to keep silence - it doesn't get any messages from server :(. Only ping.

**Comment by nuclearace** [comment] 2015-04-01 12:57
Hm, when that happens does the server think that the client disconnected? Because there's a bug with socket.io that even if there's a transport/parser error it'll still keep the connection open and send pings.

**Comment by waphumanoid** [comment] 2015-04-04 08:34
it is pretty complicated to catch it since I have no access to the server logs but I'll try...

**Closed** 2015-06-05 11:24 UTC
Labels: unconfirmed
