### ISSUE TITLE
Socket Disconnected

### ISSUE THREAD

**Issue by oinsider** [nuclearace/Socket.IO-Client-Swift#126] opened 2016-06-08 09:37 UTC
I have a node server behind a haproxy and I can connect to node's socket with Chrome's Simple WebSocket client and through an iOS simple SocketRocket client, but not with the Socket.IO swift client. The connection ends with an NSStream end encountered event (NSStreamEventEndEncountered)

I have tested it in from the 5.0.0 version up to the 6.1.2 and the last development branch.

<img width="740" alt="captura de pantalla 2016-06-08 a las 11 20 21" src="https://cloud.githubusercontent.com/assets/645151/15889849/1f363a20-2d6d-11e6-846b-15efe69a9e77.png">
<img width="843" alt="captura de pantalla 2016-06-08 a las 11 21 00" src="https://cloud.githubusercontent.com/assets/645151/15889848/1f34d6ee-2d6d-11e6-89a8-d81f177cdff4.png">
<img width="1073" alt="captura de pantalla 2016-06-08 a las 11 22 25" src="https://cloud.githubusercontent.com/assets/645151/15889847/1f342a00-2d6d-11e6-9849-7d897a04b38b.png">

**Comment by nuclearace** [comment] 2016-06-08 12:29
If you want to connect directly to your server with WebSockets then do

```swift
let socket = SocketIOClient(url: NSURL(string: "http://myserver.com/")!, options: [.ForceWebsockets(true)])
```

Or the obj-c equivalent.

**Comment by orozkoinsider** [comment] 2016-06-08 13:28
Same result
<img width="1074" alt="captura de pantalla 2016-06-08 a las 15 25 53" src="https://cloud.githubusercontent.com/assets/645151/15895804/824446e6-2d8d-11e6-92dd-e2d5072ed610.png">

**Comment by nuclearace** [comment] 2016-06-08 13:58
What version of socket.io is the server using?

**Comment by orozkoinsider** [comment] 2016-06-08 13:59
1.4.6

**Comment by nuclearace** [comment] 2016-06-08 14:03
Are your url and ports correct? Because I've tested just plain socket.io servers and Forcewebsockets and it works fine.

**Comment by orozkoinsider** [comment] 2016-06-08 14:06
we have a haproxy redirecting the traffic, does the library check the responses of the server?

**Comment by nuclearace** [comment] 2016-06-08 14:07
You may have to connect directly to the server, I have never tested proxy stuff. I don't think the WebSocket library supports SOCKS atm. But there's a pull request that is looking to add it.

**Comment by orozkoinsider** [comment] 2016-06-08 14:08
I have just check the react-native socket.io and the Android clients and both work ok

**Comment by nuclearace** [comment] 2016-06-08 14:09
You could probably not force websockets. Since I would think NSUSRLSession would be able to handle proxy stuff.

**Comment by nuclearace** [comment] 2016-06-08 14:14
https://github.com/daltoniam/Starscream/pull/202

**Comment by orozkoinsider** [comment] 2016-06-08 14:15
Without forcing seems like uses polling all the time, and at some point I get the session ID unknown
Got message: {"code":1,"message":"Session ID unknown"}

**Comment by nuclearace** [comment] 2016-06-08 14:18
Correct, because it can't connect the websocket because of the proxy. That's why socket.io uses polling before it switches to Websockets. As for the unknown session ID, I have no idea about that. That shouldn't happen if the request is going to the same socket.io server and the connection hasn't been closed.

**Comment by nuclearace** [comment] 2016-06-08 14:20
If you must have Websockets then you might have to connect directly to your server, bypassing the proxy.

**Comment by orozkoinsider** [comment] 2016-06-08 14:37
I can't do that, and the strange thing is that with the javascript and Android clients just work.

**Comment by nuclearace** [comment] 2016-06-08 14:41
They both use Websocket libraries that support SOCKS proxies I assume. You'll have to wait for the above pull request to be merged. And then I'll update the websocket library here.

**Comment by orozkoinsider** [comment] 2016-06-08 14:52
I tried oldshuren's proxy-connect repo with the proxy fix and doesn't seem to work

<img width="661" alt="captura de pantalla 2016-06-08 a las 16 51 05" src="https://cloud.githubusercontent.com/assets/645151/15898608/464e300a-2d99-11e6-9ae4-4d9b1c4a367a.png">

**Comment by orozkoinsider** [comment] 2016-06-08 14:53
I will try to use a react-native view as a workaround to this problem, I don´t know if the issue is in the client library or in the haproxy config

**Comment by nuclearace** [comment] 2016-06-08 15:02
Well your url in the screenshot for the WebSocket example is wrong. It'd have to be the same as in SocketRocket.

**Comment by orozkoinsider** [comment] 2016-06-08 15:06
I have tried ws, wss, http and https protocols, and always prints websocketDidDisconnect

**Closed** 2016-11-14 08:12 UTC
